#!/usr/bin/env python3
"""Генерирует Compose runtime-реестр из канонического docs/design/icons/registry.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/design/icons/registry.json"
OUTPUT = ROOT / "composeApp/src/commonMain/kotlin/brain/studio/ui/GeneratedKashaIcons.kt"


def kotlin_string(value: str | None) -> str:
    if value is None:
        return "null"
    return json.dumps(value, ensure_ascii=True)


def number(shape: dict, key: str) -> str:
    value = shape.get(key)
    return "null" if value is None else f"{float(value):g}f"


def shape_code(shape: dict) -> str:
    fill = shape.get("fill") == "currentColor"
    stroke = shape.get("stroke", "currentColor") != "none"
    opacity = float(shape.get("opacity", 1))
    return (
        "GeneratedIconShape("
        f"type={kotlin_string(shape['type'])},part={kotlin_string(shape['part'])},d={kotlin_string(shape.get('d'))},"
        f"x={number(shape,'x')},y={number(shape,'y')},width={number(shape,'width')},height={number(shape,'height')},rx={number(shape,'rx')},"
        f"x1={number(shape,'x1')},y1={number(shape,'y1')},x2={number(shape,'x2')},y2={number(shape,'y2')},"
        f"cx={number(shape,'cx')},cy={number(shape,'cy')},r={number(shape,'r')},fill={str(fill).lower()},stroke={str(stroke).lower()},opacity={opacity:g}f)"
    )


def geometry_code(geometry: list[dict]) -> str:
    return "listOf(\n" + ",\n".join("            " + shape_code(shape) for shape in geometry) + "\n        )"


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    assert data["grid"] == 24 and data["strokeWidth"] == 1.8
    assert len(data["icons"]) == 42, "Canonical Kasha Icons set must contain 42 glyphs"

    icons = []
    aliases: dict[str, str] = {}
    for icon in data["icons"]:
        for alias in icon["aliases"]:
            aliases[alias] = icon["id"]
        variants = icon.get("variants", {})
        variants_code = "emptyMap()" if not variants else "mapOf(\n" + ",\n".join(
            f"            {kotlin_string(name)} to {geometry_code(geometry)}" for name, geometry in variants.items()
        ) + "\n        )"
        icons.append(
            f"    {kotlin_string(icon['id'])} to GeneratedIconDefinition(\n"
            f"        geometry={geometry_code(icon['geometry'])},\n"
            f"        variants={variants_code},\n"
            f"    )"
        )

    assert aliases.get("MAGIC") == aliases.get("TEXT_PROCESSING") == "text-processing"
    assert all(alias in aliases for alias in data["currentGlyphs"])
    alias_code = ",\n".join(f"    {kotlin_string(alias)} to {kotlin_string(icon_id)}" for alias, icon_id in sorted(aliases.items()))

    output = f'''// GENERATED by scripts/generate-kasha-icons.py from docs/design/icons/registry.json. Do not edit.
package brain.studio

internal data class GeneratedIconShape(
    val type: String,
    val part: String,
    val d: String? = null,
    val x: Float? = null,
    val y: Float? = null,
    val width: Float? = null,
    val height: Float? = null,
    val rx: Float? = null,
    val x1: Float? = null,
    val y1: Float? = null,
    val x2: Float? = null,
    val y2: Float? = null,
    val cx: Float? = null,
    val cy: Float? = null,
    val r: Float? = null,
    val fill: Boolean = false,
    val stroke: Boolean = true,
    val opacity: Float = 1f,
)

internal data class GeneratedIconDefinition(
    val geometry: List<GeneratedIconShape>,
    val variants: Map<String, List<GeneratedIconShape>> = emptyMap(),
)

internal const val GENERATED_KASHA_ICON_STROKE = {float(data['strokeWidth']):g}f
internal val generatedKashaIcons: Map<String, GeneratedIconDefinition> = mapOf(\n{',\n'.join(icons)}\n)
internal val generatedKashaIconAliases: Map<String, String> = mapOf(\n{alias_code}\n)
'''
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Kasha Icons runtime registry: {len(data['icons'])} glyphs, {len(aliases)} aliases")


if __name__ == "__main__":
    main()
